language: java
jdk:
  - openjdk11

services:
  - docker

before_install:
  - mvn -N io.takari:maven:wrapper

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B
  - docker-compose up --detach
